#pragma once
#include <d3d12.h>

constexpr DXGI_FORMAT DEFAULT_BACK_BUFFER_FORMATT = DXGI_FORMAT_R8G8B8A8_UNORM;
constexpr DXGI_FORMAT DEFAULT_DEPTH_STENCIL_FORMAT = DXGI_FORMAT_D24_UNORM_S8_UINT;
constexpr int NUM_SWAPCHAIN_BUFFER = 2;
